name:                gamgee
version:             0.1.0
github:              "rkaippully/gamgee"
license:             MPL-2.0
author:              "Raghu Kaippully"
maintainer:          "rkaippully@gmail.com"
copyright:           "2018 Raghu Kaippully"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/rkaippully/gamgee#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  gamgee:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cryptonite
    - aeson
